name: dscript
channels:
  - defaults
  - bioconda
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.3
  - cudatoolkit=10.0
  - h5py
  - matplotlib
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - tqdm
