name: dscript

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=10.2
  - pip=20.0
  - python=3.7
  - pytorch=1.5
  - torchvision=0.6
  - h5py
  - matplotlib
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - tqdm
