# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
cudatoolkit=10.0.130
cudnn=7.6.5=cuda10.0_0
h5py=3.1
matplotlib=3.1
numpy=1.18.5
pandas=1.1
pip=20.2
python=3.7
pytorch=1.5
scikit-learn=0.23
scipy=1.5
seaborn=0.11
setuptools=49.6
tqdm=4.42
