name: dscript

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - pip=20.0
  - cudatoolkit=10.2
  - python=3.7
  - pytorch=1.7
  - pytorch-lightning
  - h5py
  - matplotlib
  - numpy
  - omegaconf
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - tqdm
