name: dscript_web

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - pip=20.0
  - python=3.7
  - pytorch=1.5
  - h5py
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - tqdm
  - celery[redis]
  - django
  - djangorestframework
  - django-celery-results
  - django-cors-headers
  - redis
  - python-dotenv
